const mockJobsResponse = {
  data: [
    {
      employer_name: 'NRI Australia & New Zealand',
      employer_logo:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHparmJX1aWxMYx-yHBw8pQfFKz1IbTWyOl4vz&s=0',
      employer_website: null,
      employer_company_type: null,
      job_publisher: 'LinkedIn',
      job_id: 'qOUh-6c5cfIAAAAAAAAAAA==',
      job_employment_type: 'FULLTIME',
      job_title: 'Sponsorship Opportunity - Java Developer',
      job_apply_link:
        'https://nz.linkedin.com/jobs/view/sponsorship-opportunity-java-developer-at-nri-australia-new-zealand-3522269812',
      job_apply_is_direct: false,
      job_apply_quality_score: 0.5638,
      job_description:
        'G’day techies. We’re looking for international IT professionals who want to give Australia a go.\n\nIt’s easy as with NRI’s support – we’ll help you and your family with Visa requirements and cover the costs of your flights down under. Once you’re here, you’ll be working with some of the most iconic Australian brands and get to work (and play!) the Aussie way.\n\nTHE OPPORTUNITY\n\nNRI Australia and New Zealand currently have a permanent opportunity for an experienced Full Stack Java Developer.\n\nEssential Technical Skills:\n• Full Stack Java experience (including Java, Angular JS, React)\n• Experience with Cloud Platforms (AWS/Azure)\n• Good written and verbal communication skills, including the ability to communicate effectively with non-technical audiences (e.g., business users)\n\nHighly Desirable\n• Experience with API gateways and services\n• Experience with Microservices and container technologies\n• Experience working in a DevOps environment (CI/CD)\n• Node.js\n\nDesirable\n• Experience with low-code platforms (e.g., Outsystems)\n• Experience with automated testing tools\n\nWHAT MAKES US NRI?\n\nTransformative digital solutions take more than IT expertise. They take a partner you can count on. With an eye for precision and the vision to help you progress. Who can move quickly to find the right ways forward – so that you’re always ahead of tomorrow.\n\nWe’re that partner for countless businesses. Designing, implementing, and managing digital solutions that are as personalised as they are progressive. That open the doors to greater digital success – across business, government and beyond.\n\nWe deliver everything from business strategy and consulting through to infrastructure and managed IT services. We’re backed by a global reach that makes us a truly game-changing alternative in the digital services space – with local decision-making and authority. And we’re powered not just by technology, but by passionate people who are fearlessly committed to getting it right for our customers.\n\nTransformative digital solutions take the right team, making the right moves at the right time. You’ve found yours with NRI\n\nPlease note, to be eligible for this role you will need to meet minimum VISA requirements\n\nIf the above sounds like you, please click apply!\n\nDIVERSITY & INCLUSION\n\nWe celebrate the diversity of people, and we pride ourselves on ensuring everyone belongs. As an equal opportunity employer, we want to create opportunities for everyone and will consider all applications without bias.\n\nWe value our collaborative culture and work together to support a variety of community organisations and social issues.',
      job_is_remote: false,
      job_posted_at_timestamp: 1680150929,
      job_posted_at_datetime_utc: '2023-03-30T04:35:29.000Z',
      job_city: 'Auckland',
      job_state: null,
      job_country: 'NZ',
      job_latitude: -36.850883,
      job_longitude: 174.76448,
      job_benefits: null,
      job_google_link:
        'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=java+developer,+new+zealand&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=java+developer,+new+zealand&htidocid=qOUh-6c5cfIAAAAAAAAAAA%3D%3D',
      job_offer_expiration_datetime_utc: '2023-05-15T04:27:07.000Z',
      job_offer_expiration_timestamp: 1684124827,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: null,
      job_posting_language: 'en',
      job_onet_soc: '15113200',
      job_onet_job_zone: '4',
    },
    {
      employer_name: 'Spark New Zealand',
      employer_logo:
        'https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Spark_New_Zealand_logo.svg/1200px-Spark_New_Zealand_logo.svg.png',
      employer_website: 'https://www.spark.co.nz',
      employer_company_type: 'Information',
      job_publisher: 'LinkedIn',
      job_id: 'i-jDR0PssY8AAAAAAAAAAA==',
      job_employment_type: 'FULLTIME',
      job_title: 'Java Full Stack Developer - Telco',
      job_apply_link:
        'https://nz.linkedin.com/jobs/view/java-full-stack-developer-telco-at-spark-new-zealand-3138729504',
      job_apply_is_direct: false,
      job_apply_quality_score: 0.5644,
      job_description:
        "We are Spark, New Zealand's largest and multi-brand digital services company offering mobile, fixed and IT products and services to millions of New Zealand consumers and businesses. Home to inspired, forward thinkers. Spark people are at the heart of our purpose to help all of New Zealand win big in a digital world.\n\nSpark operates in an exciting and constantly evolving industry, where the pace of change brings new and unique challenges every day. We have adopted an \"Agile\" way of working to allow us to meet the fast-changing needs of our customers. Agile will bring a transparent, collaborative environment with highly productive teams who are empowered to deliver better outcomes for our customers.\n\nIt's our belief that this way of working provides an enriched career experience for you, both in terms of the role you perform and your professional growth.\n\nWe have an exciting opportunity to find a Full-stack Developer in our Order Management chapter for TelcoCloud. You'll embrace new challenges and learning opportunities. You will provide the experience and skills needed to collaborate, embed, support and grow a successful agile culture.\n\nWhat You're Responsible For\n\nYou will be a self-driven person with a can-do attitude as part of the Order Management chapter and responsible for application design, development, testing, production support and problem resolution work items with significant autonomy and independence. Scope of work includes small system enhancements to complex projects.\n\nKey Responsibilities Include\n• Design, implement and test functions for microservices and legacy systems\n• Production incidents resolving including on-call\n• Functional and Non-functional testing support\n\nGeneral Skills\n• Delivery focused with hands-on skills - able to communicate and articulate problems and solutions.\n• Commitment to delivering positive outcomes with teammates.\n• Ability to effectively work with vendors and solution partners.\n\nIT Skills & Experience\n• 5yr+ Strong experience with Java programming and tooling: Spring boot Framework, JDK11 and or JDK17, Maven\n• 5yr+ Strong experience with SPA : ReactJS , Jest , Axios\n• Experience with BPMN engines like Camunda 7&8 and/or Activiti is prefered\n• A Telecom background with order management system experience like Ericsson Order Care is prefered\n• Hands-on experience with Integration technologies such as SOAP, REST, gRPC, JMS, Kafka etc.\n• Hands-on experience with container platforms: Docker, Openshift/K8s , AWS\n• Experience with databases: PostgresSQL.\n• Experience with Elasticsearch and MongoDB is a plus",
      job_is_remote: false,
      job_posted_at_timestamp: 1680101796,
      job_posted_at_datetime_utc: '2023-03-29T14:56:36.000Z',
      job_city: 'Auckland',
      job_state: null,
      job_country: 'NZ',
      job_latitude: -36.850883,
      job_longitude: 174.76448,
      job_benefits: null,
      job_google_link:
        'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=java+developer,+new+zealand&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=java+developer,+new+zealand&htidocid=i-jDR0PssY8AAAAAAAAAAA%3D%3D',
      job_offer_expiration_datetime_utc: '2023-08-17T08:07:31.000Z',
      job_offer_expiration_timestamp: 1692259651,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 60,
        experience_mentioned: true,
        experience_preferred: true,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: null,
      job_posting_language: 'en',
      job_onet_soc: '15113300',
      job_onet_job_zone: '4',
    },
    {
      employer_name: 'Peoplebank NZ',
      employer_logo: null,
      employer_website: null,
      employer_company_type: null,
      job_publisher: 'Peoplebank NZ',
      job_id: 'fz5EwVpU6LcAAAAAAAAAAA==',
      job_employment_type: 'FULLTIME',
      job_title: 'Senior Java Developer',
      job_apply_link: 'https://www.peoplebank.co.nz/job/senior-java-developer-1',
      job_apply_is_direct: false,
      job_apply_quality_score: 0.815,
      job_description:
        'Our client is an established NZ organisation who are currently experiencing a large and exciting period of growth. There are multiple projects coming up and as such are currently recruiting for a Senior Java Developer to join their team on permanent basis.\n\nThis is an exciting time to join their business, where you will be encouraged to grow and learn and help them to deliver leading edge projects working with some of the latest technology stack.\n\nResponsibilities\n• Design and document Java software solutions that meet business needs and requirements\n• Code and test software solutions that complies with specifications within required timeframes to the specified quality levels.\n• Identify and discuss with project, product or development leaders any issues identified in requirements and design\n• Develop and execute Unit and Integration tests to provide a suitable level of code coverage\n• Ensure functional software that fully and seamlessly integrates into the production environment\n• Taking ownership of the end-to-end development lifecycle. This will involve working closely with Business Analysts & stakeholders to understand their needs and create excellent solutions\n\nYou\n• Strong knowledge of Java is essential with 5+ years in Java development roles\n• Good understanding of database concepts and strong knowledge of SQL\n• Analytical problem-solving skills and attention to detail\n• Possess an ability to deliver in a high-volume environment\n• Strong customer delivery experience - be comfortable working closely with stakeholders and other business units\n• Knowledge of web service technologies advantageous (e.g. REST, SOAP, XML, JSON, WS Security)\n• Knowledge of other programming language (e.g. .Net, Python, etc.) advantageous but not essential\n\nTo be considered for this role you must have lived at least 10 years in NZ.\n\nThis is a fantastic opportunity to join a highly renowned organisation where you will be rewarded with amazing benefits and job satisfaction.\n\nIf you are interested, or know someone who may be, then please contact Clare O’Sullivan on 021425273 or apply online.',
      job_is_remote: false,
      job_posted_at_timestamp: 1675741565,
      job_posted_at_datetime_utc: '2023-02-07T03:46:05.000Z',
      job_city: 'Auckland',
      job_state: null,
      job_country: 'NZ',
      job_latitude: -36.850883,
      job_longitude: 174.76448,
      job_benefits: null,
      job_google_link:
        'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=java+developer,+new+zealand&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=java+developer,+new+zealand&htidocid=fz5EwVpU6LcAAAAAAAAAAA%3D%3D',
      job_offer_expiration_datetime_utc: '2023-04-26T23:59:59.000Z',
      job_offer_expiration_timestamp: 1682553599,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: 'Senior',
      job_posting_language: 'en',
      job_onet_soc: '15113200',
      job_onet_job_zone: '4',
    },
    {
      employer_name: 'Talent New Zealand',
      employer_logo: null,
      employer_website: null,
      employer_company_type: null,
      job_publisher: 'Talent International (NZ)',
      job_id: 'gmN1rDveRqcAAAAAAAAAAA==',
      job_employment_type: 'FULLTIME',
      job_title: 'Java Developer',
      job_apply_link: 'https://www.talentinternational.co.nz/job/java-developer-9',
      job_apply_is_direct: false,
      job_apply_quality_score: 0.817,
      job_description:
        "Opportunity knocks...\n• Well known financial services provider business located right in the heart of Auckland City.\n• Play a part in a small close knit team working to build quality in house applications.\n• Learn new skills and share your knowledge\n• Beautiful, modern offices\n\nWhy you're special…\n• You hold confidence with the fundamentals of Java and have worked with some front end technologies\n• Previous experience using Java, Springboot, and understanding of JDBC.\n• You have good communication skills\n• Team oriented and hold a willingness to learn\n\nAnd ... What's in it for you?\n• Gorgeous offices in the heart of Auckland CBD\n• Work alongside colleagues who are passionate about coding and building quality applications\n• Produce in house, internal applications, and work on some greenfield projects\n• Opportunity to get your foot in the door within financial services\n• Dedicated, hardworking team\n• Flat structure with great team collaboration\n\nInterested?\n\nLet's get started! Please apply now for your application to be immediately considered.",
      job_is_remote: false,
      job_posted_at_timestamp: 1680501031,
      job_posted_at_datetime_utc: '2023-04-03T05:50:31.000Z',
      job_city: 'Auckland',
      job_state: null,
      job_country: 'NZ',
      job_latitude: -36.850883,
      job_longitude: 174.76448,
      job_benefits: null,
      job_google_link:
        'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=java+developer,+new+zealand&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=java+developer,+new+zealand&htidocid=gmN1rDveRqcAAAAAAAAAAA%3D%3D',
      job_offer_expiration_datetime_utc: '2023-05-03T23:59:59.000Z',
      job_offer_expiration_timestamp: 1683158399,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: null,
      job_posting_language: 'en',
      job_onet_soc: '15113200',
      job_onet_job_zone: '4',
    },
    {
      employer_name: 'GBG',
      employer_logo: 'https://www.gbgplc.com/assets/img/gbg-logo-800.png',
      employer_website: 'http://www.gbgplc.com',
      employer_company_type: 'Information',
      job_publisher: 'Jobs By Workable',
      job_id: 'KSmKHV2HxI0AAAAAAAAAAA==',
      job_employment_type: 'FULLTIME',
      job_title: 'Java Developer (3429)',
      job_apply_link:
        'https://jobs.workable.com/view/9QKzspFWoY9Au9v9NQQBAt/java-developer-(3429)-in-auckland-at-gbg',
      job_apply_is_direct: true,
      job_apply_quality_score: 0.5711,
      job_description:
        "About GBG:\n\nGBG is the leading expert in global digital identity. We combine our powerful technology, the most accurate data coverage and our talented team to deliver award-winning location intelligence, identity verification and fraud prevention solutions.\n\nWith over 30 years’ experience, we bring together a team of over 1,250 dedicated experts with local industry insight from around the world to make it easy for businesses to identify and verify customers and locations, protecting everyone, everywhere from fraud.\n\nWhy you should be@GBG\n\n(With the 95% of our team members that recommend us as a great place to work)\n• We make the world a safer place\n• We trust each other and win together\n• We are local experts in a global business\n• We want you to be yourself\n• We grow when you grow\n\nAbout the team:\n\nCloudcheck – A GBG product. Cloudcheck is New Zealand’s leading Electronic Identity Verification Service. We a small close-knit team based in Auckland. Our sole focus is to work on the Cloudcheck product. The team is consists of Sales, Account Management and Product Development/Engineering, led by the founder of the original CloudCheck company.\n\nThe Role:\nAs a Java Developer/Java Software Engineer you will work closely with the Senior Developer to gather requirements, design, develop enhancements and support the products and supporting production system. It is a true all-round role for and and requires a quick learner with a good attention to detail and ability to prioritise their work. This excellent opportunity will mean that you are an important contributor to one of GBG’s leading SaaS identity products that is used by many of the region's biggest and most progressive businesses.\n\nWhat you will do:\n• Development\n• Work with the business to refine development requirements and contribute to the design the requirements\n• Deliver development requirements in a timely manner\n• Help refine and deliver new product ideas\n• Enhancement\n• Identify product and process enhancements\n• Maintenance & Support\n• Maintain & improve the stability of Cloudcheck\n• Fix bugs and release these fixes in a timely and professional manner on a schedule to suit business requirements\n• Look for processing improvements and implement where necessary\n• When escalated by the business, support external IT contacts with their IT issue\n\nWhat we're looking for\n\nEssential\n• Java web development experience JSP / tag libraries, MVC development\n• API integrations – RESTful Web Services / SOA\n• Database integrations – Hibernate, PostgreSQL\n• Ability to work independently\n• Legally entitled to work in New Zealand\n• Desire to Continually develop skills / knowledge to support your personal development\n\nDesired\n• AWS/Cloud experience\n• Auckland based\n\nBehaviours we'd like to see:\n\nTo find out more:\n\nClick here to see more about what’s important to us, including our Work When and Where You Want policy, our commitment to ESG, I&D and much more.\n\nTo chat to the Talent Attraction team and find out more about our benefits, drop an email to behired@gbgplc.com and we’ll be in touch!\n\nMake life@GBG work for you.",
      job_is_remote: false,
      job_posted_at_timestamp: 1679443200,
      job_posted_at_datetime_utc: '2023-03-22T00:00:00.000Z',
      job_city: 'Auckland',
      job_state: null,
      job_country: 'NZ',
      job_latitude: -36.850883,
      job_longitude: 174.76448,
      job_benefits: null,
      job_google_link:
        'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=java+developer,+new+zealand&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=java+developer,+new+zealand&htidocid=KSmKHV2HxI0AAAAAAAAAAA%3D%3D',
      job_offer_expiration_datetime_utc: null,
      job_offer_expiration_timestamp: null,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 360,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: null,
      job_posting_language: 'en',
      job_onet_soc: '15113200',
      job_onet_job_zone: '4',
    },
    {
      employer_name: 'Peoplebank NZ',
      employer_logo: null,
      employer_website: null,
      employer_company_type: null,
      job_publisher: 'Peoplebank NZ',
      job_id: 'oa9XIAqNI4oAAAAAAAAAAA==',
      job_employment_type: 'FULLTIME',
      job_title: 'Java Software Engineer',
      job_apply_link: 'https://www.peoplebank.co.nz/job/java-software-engineer-1',
      job_apply_is_direct: false,
      job_apply_quality_score: 0.815,
      job_description:
        '• Can you create great software solutions?\n• Do you enjoy an environment that promotes innovative solutions to support intelligence investigations?\n• Would you like the freedom to try new things? This might be the right place for you…..\nThe Organisation:\nThe New Zealand Security Intelligence Service (NZSIS) is looking for an experienced and highly competent Software Engineer with the necessary ‘tight-lipped’ skills to get amongst enhancing Aotearoa’s national security.\nYou will work for a national organisation with diverse, talented, and committed individuals who are anything but ordinary – creating a better and safer environment for all New Zealanders. With exciting growth opportunities within the community, and where curiosity and inquisitive minds are encouraged, the work you do with the NZSIS will be like nothing you have ever done before.\n\nThis next step could shape your career forever.\n\nAbout the Environment:\nThis is an outstanding opportunity to develop your world class Software Engineering skillset in a unique environment.\n• Access unparalleled training and many opportunities for advancement\n• Ownership of making your own projects, owning the role with its’ risks and rewards\n• Work with a range of technology and situations that will see you demonstrate your problem-solving capacity to the utmost\n• This is an extremely supportive environment where you will be provided with the tools and training to excel in a role with real meaning\nAbout the Role:\nYou will work within a team of creative software developers who work on core internal applications.\n\nThe position will focus on:\n• Data integration & Integrity from multiple data sources. You will ensure that the information is housed in a robust and usable manner\n• Creation of an environment where information can be easily accessible and created into dashboards & reports as required\n• Application development & enhancements, ensuring the core application & applicable systems are future-proofed and resilient\n• Taking ownership of the end-to-end development lifecycle. This will involve working closely with Business Analysts & stakeholders to understand their needs and create excellent solutions\n• This role will give you autonomy to find out-of-the-box solutions, and as such you will need to be curious and always on the lookout for a better way of creating brilliant outcomes.\nAbout You:\nDo you really know your stuff? Are your development skills top-notch and able to create elegant, efficient, secure solutions?\n\nYou will:\n• Be a highly skilled and competent software engineering expert with the drive to enable the realisation of successful software\n• Able to contribute to technical design of software systems and can troubleshoot technical issues\n• Be comfortable working closely with stakeholders and other business units\n• Have exceptional skills and experience in a range of technologies including Java, Python; Perl; Java; C#, C, C++; Swift; Assembler; Bash or Shell; HTML; ASP; JSP\n• Have experience with the full SDLC including testing and test automation\n• Have an understanding of development in an Agile environment\n• Have coherent and efficient development skills\n• Possess an ability to deliver in a challenging environment\nExceptional Benefits Package:\n• Medical Insurance: Medical and Vision Care subsidy\n• Social Sports Teams and Staff Networks\n• Paid Certifications and Qualifications Available\n• Childcare Allowance: For pre-school children\n• Annual Leave: 4 weeks plus 6 additional days\n• Sick Leave: 15 Days\n• Flexible Start & Finish Times\nTo apply:\nFor more information including a position description and further information on the application process, apply now.\n\nIMPORTANT: To be eligible for employment within the NZIC you must have been a NZ citizen for at least 10 years. Alternatively, you must hold a current NZ Residency Class Visa and ideally have been a citizen of UK, USA, Canada, or Australia for at least 10 years.\n\nTo check your eligibility for Top Secret Special clearance please visit: https://www.protectivesecurity.govt.nz/personnel-security/managing-insider-risk/clearances/eligibility-tool/',
      job_is_remote: false,
      job_posted_at_timestamp: 1675378267,
      job_posted_at_datetime_utc: '2023-02-02T22:51:07.000Z',
      job_city: 'Auckland',
      job_state: null,
      job_country: 'NZ',
      job_latitude: -36.850883,
      job_longitude: 174.76448,
      job_benefits: null,
      job_google_link:
        'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=java+developer,+new+zealand&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=java+developer,+new+zealand&htidocid=oa9XIAqNI4oAAAAAAAAAAA%3D%3D',
      job_offer_expiration_datetime_utc: '2023-04-26T23:59:59.000Z',
      job_offer_expiration_timestamp: 1682553599,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: true,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: 'Software engineer',
      job_posting_language: 'en',
      job_onet_soc: '15113200',
      job_onet_job_zone: '4',
    },
    {
      employer_name: 'Beyond Recruitment',
      employer_logo:
        'https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id=100028835396881',
      employer_website: null,
      employer_company_type: null,
      job_publisher: 'Beyond Recruitment',
      job_id: 'nqVX0qV8H1UAAAAAAAAAAA==',
      job_employment_type: 'FULLTIME',
      job_title: 'Java Developer',
      job_apply_link: 'https://www.beyondrecruitment.co.nz/job/java-developer-9',
      job_apply_is_direct: false,
      job_apply_quality_score: 0.9079,
      job_description:
        "• Java Developer\n• Contract\n• Auckland\n\nAbout the role:\n\nSeeking Contract Java Developers who are experienced in working within Enterprise environments. You will have worked with some of the latest tools in Open Stack along with strong ability to work in AWS Environments.\n\nSkills Required:\n• Java Version 8 and over\n• J Unit\n• Microservices/ Kafka/ ActiveMQ etc\n• Maven\n• IntelliJ\n• JMeter\n• AWS\n• DevOps and CI/CD\n• Agile\n\nRegister your interest today to discuss opportunities!\n\nWe'd love to hear from you, if this is the right role for you - APPLY now or you can reach out to Nikhil Maharaj at nikhil.maharaj@beyond.co.nz call on 021 222 7526.\n\nEssential: Eligibility to work in New Zealand is very essential and currently residing in New Zealand.\n\nRef: 113289\n\nBeyond Recruitment - Technology, Transformation & Digital, connecting IT talent with IT opportunities. Visit www.beyond.co.nz for more roles and information.",
      job_is_remote: false,
      job_posted_at_timestamp: 1679966120,
      job_posted_at_datetime_utc: '2023-03-28T01:15:20.000Z',
      job_city: 'Auckland',
      job_state: null,
      job_country: 'NZ',
      job_latitude: -36.850883,
      job_longitude: 174.76448,
      job_benefits: null,
      job_google_link:
        'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=java+developer,+new+zealand&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=java+developer,+new+zealand&htidocid=nqVX0qV8H1UAAAAAAAAAAA%3D%3D',
      job_offer_expiration_datetime_utc: '2023-04-27T23:59:59.000Z',
      job_offer_expiration_timestamp: 1682639999,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: null,
      job_posting_language: 'en',
      job_onet_soc: '15113200',
      job_onet_job_zone: '4',
    },
    {
      employer_name: 'Parrot Analytics',
      employer_logo:
        'https://www.enterpriseangels.co.nz/wp-content/uploads/2019/05/Parrot-Logo.jpg',
      employer_website: 'https://www.parrotanalytics.com',
      employer_company_type: null,
      job_publisher: 'The Muse',
      job_id: 'DWaNeZzBSCIAAAAAAAAAAA==',
      job_employment_type: 'FULLTIME',
      job_title: 'Senior API Developer | Java',
      job_apply_link:
        'https://www.themuse.com/jobs/parrotanalytics/senior-api-developer-java-518f7f',
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6752,
      job_description:
        "We are on a mission to connect creators and consumers around the world. We believe in the magic of content and the impact it has on peoples life.\n\nAt Parrot Analytics, we deliver the world's leading content demand analytics built on the largest demand database to bring the science to the art of content. Rapidly establishing itself as one of the most innovative companies in Hollywood, our products are helping drive a new era in the entertainment industry as we are empowering our clients to make the most powerful data-driven decisions every day.\n\nWe are a data science company that empowers media companies, brands and agencies (think Google, Amazon, Facebook, Disney, HBO, Netflix, Lego, Apple) to understand global audience demand for content. Wielding the world's largest audience behaviour data sets, we have developed the world's only global cross-platform, country-specific Content Demand Measurement System.\n\nThe Role\n\nAs a Senior Software Engineer in the API Team, you will build and maintain APIs, critical applications and infrastructure predominantly built on AWS cloud to expose our data and analytics to multiple consumers.\n\nYou will work collaboratively with a team of world class engineers, data scientists and industry insights analysts to understand what they need to get their jobs done. You care deeply about the accuracy, availability and security of our core data platform whilst being highly passionate about monitoring metrics and adapting new technologies relevant to platform and business.\n\nYou are an ambitious leader in your own right, a self-starter and an organized teammate who thrives in a fast growing, dynamic, results driven environment. If you want to be known for playing a key role in building & maintaining the technology behind the global entertainment idustry's first ever measure of content popularity, then this role is the best fit for you.\n\nRequirements\n• Solid foundation in software engineering with 6+ years of professional software development experience.\n• High proficiency in Java, SpringBoot.\n• Production experience with designing and developing RESTful and/or GraphQL APIs in high throughput applications in terms of number of calls and volume of load processing.\n• Highly competent in SQL Databases (MySQL, PostgreSQL), ORM frameworks and performance tuning techniques.\n• Empathy for customers, teammates, and other stakeholders\n• A hands on problem-solver who loves working as part of a team, strives for continuous improvement and is \"fascinated by data\" (curious for the extracting insights out of it).\n• Excellent team player with good communication skills - you need to be a great listener that understands the needs of the business and can convert these into clear and easily understood specifications & are able to present this across the teams\n\nBenefits\n\nAt Parrot, you will be in a role you love and work with people you will enjoy sharing life with. We are a diverse team from every corner of the world putting our best foot forward to live our values and master our strengths.\n\nYou will get the encouragement, support, flexibility and resources you need to succeed, learn and grow in the role and in your career.\n\nHere are some of our benefits:\n• Flexible working - location and hours (remote first with office options)\n• Opportunity to take part in the Employee Share Options Plan\n• US$1K to spend on training/development every year\n• Enhanced paid parental leave - 12 weeks for primary carer and 4 weeks for secondary carer\n• Birthday leave\n• Bi-annual salary reviews.\n\nWant to learn more about what we do?\n\nMore about what we are building here (:\n\nTo explore other opportunities we have on offer and learn more about us, visit: https://parrot-analytics.workable.com/",
      job_is_remote: true,
      job_posted_at_timestamp: 1665662274,
      job_posted_at_datetime_utc: '2022-10-13T11:57:54.000Z',
      job_city: 'Auckland',
      job_state: null,
      job_country: 'NZ',
      job_latitude: -36.850883,
      job_longitude: 174.76448,
      job_benefits: null,
      job_google_link:
        'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=java+developer,+new+zealand&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=java+developer,+new+zealand&htidocid=DWaNeZzBSCIAAAAAAAAAAA%3D%3D',
      job_offer_expiration_datetime_utc: null,
      job_offer_expiration_timestamp: null,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 72,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: 'Senior',
      job_posting_language: 'en',
      job_onet_soc: '15113200',
      job_onet_job_zone: '4',
    },
    {
      employer_name: 'Reesby It',
      employer_logo:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRq7qfaxX3sXbOBjUjhKeepMmpRjfPu5twp4CnJ&s=0',
      employer_website: null,
      employer_company_type: null,
      job_publisher: 'GrabJobs',
      job_id: '3VLO7mtzcbsAAAAAAAAAAA==',
      job_employment_type: 'FULLTIME',
      job_title: 'Java Developer - Get Hired Fast',
      job_apply_link:
        'https://grabjobs.co/nz/job/full-time/technology/java-developer-get-hired-fast-15520494',
      job_apply_is_direct: false,
      job_apply_quality_score: 0.5949,
      job_description:
        "We are searching for a motivated Java Developer to join our growing team at Reesby IT in Auckland, Auckland.\nGrowing your career as a Full Time Java Developer is a terrific opportunity to develop relevant skills.\nIf you are strong in communication, adaptability and have the right personality for the job, then apply for the position of Java Developer at Reesby IT today!\n\nReesby are looking for an experienced Java Developer who will join our clients talented software team that works on innovative payment applications. Your duties will include managing Java application development while providing expertise in the full software development lifecycle, from concept and design to testing.\n\nYou should have good experience in building high-performing, scalable, enterprise-grade applications and be able to write clean code and ensure your programs run properly. We also expect you to be passionate about building software and perform well working in a team, along with developers, engineers and web designers.\nJava Developer responsibilities are:\n• Design and develop high-volume, low-latency applications for mission-critical systems and delivering high-availability and performance\n• Create well designed, testable, efficient code\n• Participate in all phases of the development lifecycle\n• Assist in preparation and production of releases of software components\n• Ensure designs are in compliance with specifications\n• Investigate alternatives and technologies and present them for architectural review, in order to support continuous improvement\n\nJava Developer requirements are:\n• 2+ years' experience of working on a Java Developer position\n\nPrevious payments/ SDK experience /aws\n\nAny exposure with fintech businesses micro services\n• Solid experience in software development, and particularly in test-driven development\n• Significant experience in designing and developing applications using Java EE platforms\n• Excellent knowledge of Java and JEE internals, such as Classloading, Memory Management, Transaction management and so on\n• Experience of Object Oriented analysis and design using common design patterns.\n• Good knowledge of Relational Databases, SQL and ORM technologies, including JPA2 and Hibernate\n• Good knowledge of at least one popular web framework, such as JSF, Wicket, GWT, Spring MVC and so on\n• Certification of a Sun Java Developer\n• BS or MS degree in Computer Science, Engineering or other related area\n\nEmployment Type: FULL_TIME\nBenefits of working as a Java Developer in Auckland, Auckland:\n\n● Learning opportunities\n● Opportunities to grow\n● Attractive package",
      job_is_remote: false,
      job_posted_at_timestamp: 1679443200,
      job_posted_at_datetime_utc: '2023-03-22T00:00:00.000Z',
      job_city: 'Auckland',
      job_state: null,
      job_country: 'NZ',
      job_latitude: -36.850883,
      job_longitude: 174.76448,
      job_benefits: null,
      job_google_link:
        'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=java+developer,+new+zealand&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=java+developer,+new+zealand&htidocid=3VLO7mtzcbsAAAAAAAAAAA%3D%3D',
      job_offer_expiration_datetime_utc: '2023-04-22T00:00:00.000Z',
      job_offer_expiration_timestamp: 1682121600,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 24,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: true,
        degree_preferred: true,
        professional_certification_mentioned: true,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: null,
      job_posting_language: 'en',
      job_onet_soc: '15113200',
      job_onet_job_zone: '4',
    },
    {
      employer_name: 'Myjobspace',
      employer_logo:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYpvo73b_jwJT1H_9agLsMzWD5zxqKA1nAo10o&s=0',
      employer_website: null,
      employer_company_type: null,
      job_publisher: 'Talent.com',
      job_id: '8UQSxD4molcAAAAAAAAAAA==',
      job_employment_type: 'FULLTIME',
      job_title: 'Java Developer',
      job_apply_link: 'https://nz.talent.com/view?id=07af29caf7a6',
      job_apply_is_direct: false,
      job_apply_quality_score: 0.4971,
      job_description:
        'Java Developer\n\nAbout the Business\n\nJAVLN is an award winning world-class intelligent insurance and data integration software company formed in 2011.\n\nOur role is simple; we transform businesses, by leveraging the latest in data and technology to accelerate business growth and improve business efficiencies.\n\nThe Role\n\nJAVLN are on the lookout for an intermediate Java Developer who has a good understanding of the software development life cycle and current software development processes.\n\nYou will need to be flexible and willing to work on various parts of a complete system ranging from back-end systems and microservices through to front-end technology.\n\nIt is a great opportunity to work on a modern system which is designed to scale.\n\nThis is a really exciting time for JAVLN and their development team is growing rapidly, have a large pipeline of projects ahead and are offering excellent career prospects.\n\nBenefits\n• An inclusive workplace that supports career development and learning\n• Great offices based in Grey Lynn or Highbrook\n• Some flexibility to work from home\n• Exciting work atmosphere\n• Competitive remuneration package for the right candidate\n\nDay to day duties\n• Technical analysis and design\n• Participate in design reviews and workshops\n• Building and coding framework and solutions\n• Manage change control and release packaging\n• Documentation (technical, user, installation)\n• Fostering good development practice throughout the development team including code re-use, code documentation, and unit testing\n• Participating in reviews of the project plans, requirements and detailed designs by other developers\n• Estimating development efforts of product and feature development\n• Support external customers to use Javelin applications\n• Investigate and resolve technical issues as they arise\n\nYou will be operating across the following technology landscape so experience or knowledge of these systems is important\n\nJava, Spring / Spring Boot, Maven, PostgreSQL, Swagger, Thymeleaf, JavaScript / React, SASS, Bootstrap, Keycloak (SSO), Containerisation and orchestration, AWS and cloud computing, Micro-services and its application, REST API knowledge, Shell scripting, Automated testing (end-to-end integration)\n\nAdditional skills required\n• Excellent communication abilities\n• Attention to detail in all areas\n• Self-motivated with the ability to work autonomously\n• Understanding of the sales process\n• Customer focused\n• Knowledge of build systems\n• Understanding of DevOPS role and relationship (relative to development)\n• Understanding of UI design concepts\n• Understanding of Agile principles\n• Experience in the Insurance Industry (beneficial)\n\nThis opportunity is for a motivated individual to take their coding career to the next level and be part of a kiwi success story.\n\nPlease apply now with an up-to-date CV.\n\nFor any questions about the role contact Matt or Tessa at Muster recruit on 09 394 7444',
      job_is_remote: false,
      job_posted_at_timestamp: 1666396800,
      job_posted_at_datetime_utc: '2022-10-22T00:00:00.000Z',
      job_city: 'Auckland',
      job_state: null,
      job_country: 'NZ',
      job_latitude: -36.850883,
      job_longitude: 174.76448,
      job_benefits: null,
      job_google_link:
        'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=java+developer,+new+zealand&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=java+developer,+new+zealand&htidocid=8UQSxD4molcAAAAAAAAAAA%3D%3D',
      job_offer_expiration_datetime_utc: '2023-07-31T00:00:00.000Z',
      job_offer_expiration_timestamp: 1690761600,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: null,
      job_posting_language: 'en',
      job_onet_soc: '15113200',
      job_onet_job_zone: '4',
    },
  ],
};

const mockJobDetailResponse = {
  data: [
    {
      employer_name: 'Infosys',
      employer_logo:
        'https://cdn-ukwest.onetrust.com/logos/8d84415b-1b52-4bc4-8d5f-ca9a8eccaf8a/f7db8968-fc22-4620-92ac-dc05c5d2aa15/02460a41-565e-4cac-80a7-449bc8f77a72/logo-infosys.png',
      employer_website: 'http://www.infosys.com',
      employer_company_type: 'Information',
      job_publisher: 'LinkedIn',
      job_id: 'hO4waEcPOOsAAAAAAAAAAA==',
      job_employment_type: 'FULLTIME',
      job_title: 'Python Developer',
      job_apply_link: 'https://www.linkedin.com/jobs/view/python-developer-at-infosys-3542764368',
      job_apply_is_direct: false,
      job_apply_quality_score: 0.5666,
      job_description:
        'Job Description\n\nInfosys is seeking a Python Developer. This position’s primary responsibility will be to provide technical expertise and coordinate for day-to-day deliverables for the team. The chosen candidate will assist in the technical design of large business systems; builds applications, interfaces between applications, understands data security, retention, and recovery. The role holder should be able to research on technologies independently to recommend appropriate solutions & should contribute to technology-specific best practices & standards; contribute to success criteria from design through deployment, including, reliability, cost-effectiveness, performance, data integrity, maintainability and scalability; contributes expertise on significant application components, program languages, databases, operating systems, etc., and guides/mentors the team during the build and test phases.\n\nCandidate must be located within commuting distance of Pennington NJ/Jersey City NJ/NYC, NY/Dallas TX or be willing to relocate to ANY mentioned areas within 4-6 weeks.\n\nU.S. citizens and those authorized to work in the U.S. are encouraged to apply. We are unable to sponsor at this time.\n\nRequired Qualifications\n• Bachelor’s degree or foreign equivalent required from an accredited institution. Will also consider three years of progressive experience in the specialty in lieu of every year of education.\n• At least 2 years of Information Technology experience\n• Experience in Python server-side programming\n• Expert in Object Oriented Programming Concepts\n\nPreferred Qualifications\n• At least 2 years of experience in Python Server Side native programming and in framework\n• At least 2 years of experience in Java/J2EE technologies and experience in frameworks like Spring, Hibernate\n• At least 2 or more years of hands-on experience in JS Framework\n• At least 2 years of experience in software development life cycle.\n• At least 2 years of experience in Project life cycle activities on development and maintenance projects.\n• Willing to work in application/production support\n• Experience in Banking domain\n• Strong communication and Analytical skills\n• Ability to work in team in diverse/ multiple stakeholder environment\n• Experience and desire to work in a Global delivery environment\n\nThe job entails sitting as well as working at a computer for extended periods of time. Should be able to communicate by telephone, email or face to face. Travel may be required as per the job requirements.\n\nAbout Us\n\nInfosys is a global leader in next-generation digital services and consulting. We enable clients in more than 50 countries to navigate their digital transformation. With over four decades of experience in managing the systems and workings of global enterprises, we expertly steer our clients through their digital journey. We do it by enabling the enterprise with an AI-powered core that helps prioritize the execution of change. We also empower the business with agile digital at scale to deliver unprecedented levels of performance and customer delight. Our always-on learning agenda drives their continuous improvement through building and transferring digital skills, expertise, and ideas from our innovation ecosystem.\n\nInfosys is an equal opportunity employer and all qualified applicants will receive consideration without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, protected veteran status, spouse of protected veteran, or disability.',
      job_is_remote: false,
      job_posted_at_timestamp: 1680040912,
      job_posted_at_datetime_utc: '2023-03-28T22:01:52.000Z',
      job_city: 'Dallas',
      job_state: 'TX',
      job_country: 'US',
      job_latitude: 32.776665,
      job_longitude: -96.79699,
      job_benefits: null,
      job_google_link:
        'https://www.google.com/search?gl=us&hl=en&q=hO4waEcPOOsAAAAAAAAAAA%3D%3D&cs=1&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=hO4waEcPOOsAAAAAAAAAAA%3D%3D&htidocid=hO4waEcPOOsAAAAAAAAAAA%3D%3D',
      job_offer_expiration_datetime_utc: '2023-04-27T22:01:52.000Z',
      job_offer_expiration_timestamp: 1682632912,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 36,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: true,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          'The role holder should be able to research on technologies independently to recommend appropriate solutions & should contribute to technology-specific best practices & standards; contribute to success criteria from design through deployment, including, reliability, cost-effectiveness, performance, data integrity, maintainability and scalability; contributes expertise on significant application components, program languages, databases, operating systems, etc., and guides/mentors the team during the build and test phases',
          'Candidate must be located within commuting distance of Pennington NJ/Jersey City NJ/NYC, NY/Dallas TX or be willing to relocate to ANY mentioned areas within 4-6 weeks',
          'U.S. citizens and those authorized to work in the U.S. are encouraged to apply',
          'Bachelor’s degree or foreign equivalent required from an accredited institution',
          'Will also consider three years of progressive experience in the specialty in lieu of every year of education',
          'At least 2 years of Information Technology experience',
          'Experience in Python server-side programming',
          'Expert in Object Oriented Programming Concepts',
          'The job entails sitting as well as working at a computer for extended periods of time',
          'Should be able to communicate by telephone, email or face to face',
          'Travel may be required as per the job requirements',
        ],
        Responsibilities: [
          'This position’s primary responsibility will be to provide technical expertise and coordinate for day-to-day deliverables for the team',
          'The chosen candidate will assist in the technical design of large business systems; builds applications, interfaces between applications, understands data security, retention, and recovery',
        ],
      },
      job_job_title: null,
      job_posting_language: 'en',
      job_onet_soc: '15113200',
      job_onet_job_zone: '4',
      estimated_salaries: [
        {
          location: 'Dallas, TX',
          job_title: 'Python Developer',
          publisher_name: 'Indeed',
          publisher_link: 'https://www.indeed.com/career/python-developer/salaries/Dallas--TX',
          min_salary: 91473.01125907995,
          max_salary: 166958.85334173383,
          median_salary: 123580.8604583984,
          salary_period: 'YEAR',
          salary_currency: 'USD',
        },
        {
          location: 'Dallas, TX',
          job_title: 'Full Stack Python Developer',
          publisher_name: 'ZipRecruiter',
          publisher_link:
            'https://www.ziprecruiter.com/Salaries/Full-Stack-Python-Developer-Salary-in-Dallas,TX',
          min_salary: 83383,
          max_salary: 150977,
          median_salary: 129639,
          salary_period: 'YEAR',
          salary_currency: 'USD',
        },
        {
          location: 'Dallas, TX',
          job_title: 'Entry Level Python Developer',
          publisher_name: 'Salary.com',
          publisher_link:
            'https://www.salary.com/research/salary/posting/entry-level-python-developer-salary/dallas-tx',
          min_salary: 70135,
          max_salary: 115423,
          median_salary: 90421,
          salary_period: 'YEAR',
          salary_currency: 'USD',
        },
      ],
      apply_options: [
        {
          publisher: 'Indeed',
          apply_link:
            'https://www.indeed.com/viewjob?jk=078b423b732e9f7a&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic',
          is_direct: true,
        },
        {
          publisher: 'Lensa',
          apply_link:
            'https://lensa.com/python-developer-jobs/dallas/jd/28fc15ab3a8fad4c3cb11e7cff76d302?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic',
          is_direct: false,
        },
      ],
      employer_reviews: [
        {
          publisher: 'Glassdoor',
          employer_name: 'Infosys',
          score: 3.3,
          num_stars: 3.5,
          review_count: 92234,
          max_score: 5,
          reviews_link:
            'https://www.glassdoor.com/Reviews/Infosys-Reviews-E7927.htm?utm_campaign=google_jobs_reviews&utm_source=google_jobs_reviews&utm_medium=organic',
        },
        {
          publisher: 'AmbitionBox',
          employer_name: 'Infosys',
          score: 3.9,
          num_stars: 4,
          review_count: 23980,
          max_score: 5,
          reviews_link:
            'https://www.ambitionbox.com/reviews/infosys-reviews?utm_campaign=google_jobs_reviews&utm_source=google_jobs_reviews&utm_medium=organic',
        },
        {
          publisher: 'CareerBliss',
          employer_name: 'Infosys',
          score: 4,
          num_stars: 4,
          review_count: 790,
          max_score: 5,
          reviews_link:
            'https://www.careerbliss.com/infosys/reviews/?utm_campaign=google_jobs_reviews&utm_source=google_jobs_reviews&utm_medium=organic',
        },
      ],
    },
  ],
};

export { mockJobDetailResponse, mockJobsResponse };
